version: '3'
services:
  react:
    build:
      context: ./react
    image: react
    container_name: react_container
    ports:
      - "8080:8080"
    volumes:
      - ./react/app:/home/app
    tty: true
  train_api:
    build:
      context: ./node
    container_name: train_api_container
    ports:
      - "3000:3000"
    volumes:
      - ./node/train_api:/home/train_api
    tty: true
