version: 2
jobs:
  build:
    # working_directory: ./
    docker:
      - image: circleci/node:8.9

    steps:
      - checkout
      - run:
          command: ls
      # - restore_cache:
      #     key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # - run:
      #     name: System information
      #     command: |
      #       echo "Node $(node -v)"
      #       echo "Yarn v$(yarn --version)"
      # - run:
      #     name: Install dependencies
      #     command: yarn
      # - run:
      #     name: Build
      #     command: yarn run build
      # - run:
      #     name: Test
      #     command: yarn test
      # - save_cache:
      #     key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      #     paths:
      #       - ~/workspace/node_modules
      #       - ~/.cache/yarn/
      # - run: echo "A first hello"
      # - add_ssh_keys:
      #     fingerprints:
      #       - "45:bd:b8:3a:ca:f7:70:7c:0e:01:f5:3e:b4:75:79:91"
      #
      # - run:
      #     name: Start ssh-keyscan
      #     command: |
      #       ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
      #
      # - deploy:
      #     name: Start master deploy
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #           rsync -av --delete --exclude='.git' --exclude='.circleci' ./ ${USER_NAME}@${HOST_NAME}:/var/www/html/
      #       fi
